const js = require('@eslint/js');

module.exports = [
    js.configs.recommended,
    {
        files: ['public/assets/js/modules/**/*.js', 'public/assets/js/*.js'],
        languageOptions: {
            ecmaVersion: 2020,
            sourceType: 'module',
            globals: {
                window: 'readonly',
                document: 'readonly',
                navigator: 'readonly',
                console: 'readonly',
                setTimeout: 'readonly',
                clearTimeout: 'readonly',
                setInterval: 'readonly',
                clearInterval: 'readonly',
                requestAnimationFrame: 'readonly',
                cancelAnimationFrame: 'readonly',
                fetch: 'readonly',
                AbortController: 'readonly',
                FormData: 'readonly',
                FileReader: 'readonly',
                Blob: 'readonly',
                URL: 'readonly',
                URLSearchParams: 'readonly',
                HTMLElement: 'readonly',
                Element: 'readonly',
                Node: 'readonly',
                NodeList: 'readonly',
                Event: 'readonly',
                KeyboardEvent: 'readonly',
                MouseEvent: 'readonly',
                DragEvent: 'readonly',
                MutationObserver: 'readonly',
                ResizeObserver: 'readonly',
                IntersectionObserver: 'readonly',
                Map: 'readonly',
                Set: 'readonly',
                Promise: 'readonly',
                Symbol: 'readonly',
                WeakMap: 'readonly',
                WeakSet: 'readonly',
                alert: 'readonly',
                confirm: 'readonly',
                prompt: 'readonly',
                location: 'readonly',
                history: 'readonly',
                localStorage: 'readonly',
                sessionStorage: 'readonly',
                performance: 'readonly',
                getComputedStyle: 'readonly',
                matchMedia: 'readonly',
                CustomEvent: 'readonly',
                ClipboardEvent: 'readonly',
                DataTransfer: 'readonly',
                Audio: 'readonly',
                Image: 'readonly',
                CSS: 'readonly',
                crypto: 'readonly',
                module: 'readonly',
                require: 'readonly',
                Notification: 'readonly',
                WheelEvent: 'readonly',
                gtag: 'readonly',
            }
        },
        rules: {
            'indent': ['error', 4, { 'SwitchCase': 1 }],
            'quotes': ['error', 'single', { 'avoidEscape': true }],
            'semi': ['error', 'always'],
            'no-var': 'error',
            'prefer-const': 'warn',
            'no-unused-vars': ['warn', { 'argsIgnorePattern': '^_' }],
            'eqeqeq': ['error', 'always'],
            'no-eval': 'error',
            'no-implied-eval': 'error',
            'no-console': 'off',
            'no-empty': ['error', { 'allowEmptyCatch': true }],
            'no-control-regex': 'off',
            'curly': ['error', 'all'],
            'brace-style': ['error', '1tbs'],
            'comma-dangle': ['error', 'only-multiline'],
            'arrow-spacing': 'error',
            'no-trailing-spaces': 'error',
            'no-multiple-empty-lines': ['error', { 'max': 2 }],
            'space-before-function-paren': ['error', {
                'anonymous': 'never',
                'named': 'never',
                'asyncArrow': 'always'
            }],
            'keyword-spacing': 'error',
            'space-infix-ops': 'error',
            'object-curly-spacing': ['error', 'always'],
            'array-bracket-spacing': ['error', 'never'],
            'no-multi-spaces': 'error'
        }
    },
    {
        ignores: [
            'public/assets/js/vendor/**',
            'node_modules/**',
            'coverage/**',
            '**/*.min.js',
            'tests/**'
        ]
    }
];
