<?php
// Partial: Settings Modal with System Requirements Tab
// This modal includes General settings and System Requirements check
?>

<!-- Settings overlay -->
<div class="settings-overlay hidden"
    id="settings-overlay" aria-hidden="true" data-action="settings" data-open="settings">
    <div class="settings-dialog d-flex flex-col"
        role="dialog" aria-modal="true" aria-labelledby="settings-title">
        <header class="settings-header mb-4 d-flex items-center justify-between flex-shrink-0">
            <h2 id="settings-title" class="text-lg font-semibold">Pengaturan</h2>
            <button type="button" id="settings-close" data-action="settings-close" aria-label="Tutup pengaturan"
                class="settings-close-btn">✕</button>
        </header>

        <!-- Tabs Navigation -->
        <nav class="settings-tabs flex-shrink-0" role="tablist">
            <button type="button"
                class="settings-tab active"
                id="settings-tab-general" data-tab="general" role="tab" aria-selected="true"
                aria-controls="settings-panel-general">
                <svg class="w-4 h-4 d-inline-flex" viewBox="0 0 24 24" fill="currentColor">
                    <path
                        d="M19.14 12.94c.04-.31.06-.63.06-.94 0-.31-.02-.63-.06-.94l2.03-1.58c.18-.14.23-.41.12-.61l-1.92-3.32c-.12-.22-.37-.29-.59-.22l-2.39.96c-.5-.38-1.03-.7-1.62-.94l-.36-2.54c-.04-.24-.24-.41-.48-.41h-3.84c-.24 0-.43.17-.47.41l-.36 2.54c-.59.24-1.13.57-1.62.94l-2.39-.96c-.22-.08-.47 0-.59.22L2.74 8.87c-.12.21-.08.47.12.61l2.03 1.58c-.04.31-.06.63-.06.94s.02.63.06.94l-2.03 1.58c-.18.14-.23.41-.12.61l1.92 3.32c.12.22.37.29.59.22l2.39-.96c.5.38 1.03.7 1.62.94l.36 2.54c.05.24.24.41.48.41h3.84c.24 0 .44-.17.47-.41l.36-2.54c.59-.24 1.13-.56 1.62-.94l2.39.96c.22.08.47 0 .59-.22l1.92-3.32c.12-.22.07-.47-.12-.61l-2.01-1.58zM12 15.6c-1.98 0-3.6-1.62-3.6-3.6s1.62-3.6 3.6-3.6 3.6 1.62 3.6 3.6-1.62 3.6-3.6 3.6z" />
                </svg>
                Umum
            </button>
            <button type="button"
                class="settings-tab"
                id="settings-tab-language" data-tab="language" role="tab" aria-selected="false"
                aria-controls="settings-panel-language">
                <svg class="w-4 h-4 d-inline-flex" viewBox="0 0 24 24" fill="currentColor">
                    <path d="M12.87 15.07l-2.54-2.51.03-.03A17.52 17.52 0 0014.07 6H17V4h-7V2H8v2H1v1.99h11.17C11.5 7.92 10.44 9.75 9 11.35 8.07 10.32 7.3 9.19 6.69 8h-2c.73 1.63 1.73 3.17 2.98 4.56l-5.09 5.02L4 19l5-5 3.11 3.11.76-2.04zM18.5 10h-2L12 22h2l1.12-3h4.75L21 22h2l-4.5-12zm-2.62 7l1.62-4.33L19.12 17h-3.24z" />
                </svg>
                Bahasa
            </button>
            <button type="button"
                class="settings-tab"
                id="settings-tab-system" data-tab="system" role="tab" aria-selected="false"
                aria-controls="settings-panel-system">
                <svg class="w-4 h-4 d-inline-flex" viewBox="0 0 24 24" fill="currentColor">
                    <path
                        d="M20 18c1.1 0 2-.9 2-2V6c0-1.1-.9-2-2-2H4c-1.1 0-2 .9-2 2v10c0 1.1.9 2 2 2H0v2h24v-2h-4zM4 6h16v10H4V6z" />
                </svg>
                System Requirements
            </button>
        </nav>

        <div class="settings-body flex-1 overflow-y-auto">
            <!-- General Settings Panel -->
            <div class="settings-panel" id="settings-panel-general" role="tabpanel"
                aria-labelledby="settings-tab-general">
                <div class="setting-row mb-4">
                    <label for="toggle-debug" class="toggle d-flex items-center gap-3 cursor-pointer" aria-hidden="false">
                        <input type="checkbox" id="toggle-debug" class="toggle-input sr-only" role="switch"
                            aria-checked="false">
                        <span
                            class="toggle-switch"
                            aria-hidden="true">
                            <span
                                class="toggle-switch-dot"></span>
                        </span>
                        <span class="toggle-label">Aktifkan debug logging
                            (console)</span>
                    </label>
                    <p class="setting-hint">Matikan untuk
                        menghilangkan pesan debug dari konsol.</p>
                </div>

                <!-- Upload Settings -->
                <div class="setting-row mb-4">
                    <h3 class="setting-label mb-2 font-semibold" style="font-size: 0.9375rem;">Batas Upload File</h3>
                    <p class="setting-hint mb-3">Atur batas maksimum ukuran upload per jenis file. Nilai dibatasi oleh PHP <code>upload_max_filesize</code> (<span id="settings-php-upload-limit">-</span>).</p>

                    <div class="upload-limits-grid" id="upload-limits-grid">
                        <!-- Rows generated by JS -->
                    </div>
                </div>
            </div>

            <!-- Language Panel -->
            <div class="settings-panel hidden" id="settings-panel-language" role="tabpanel"
                aria-labelledby="settings-tab-language">
                <div class="setting-row mb-4">
                    <label class="setting-label mb-2 d-block font-medium">Bahasa Tampilan</label>
                    <p class="setting-hint mb-3">Pilih bahasa tampilan aplikasi.</p>
                    <div class="language-options d-flex flex-col gap-2" id="language-options">
                        <!-- Language options will be populated by JS -->
                    </div>
                </div>
            </div>

            <!-- System Requirements Panel -->
            <div class="settings-panel hidden" id="settings-panel-system" role="tabpanel"
                aria-labelledby="settings-tab-system">
                <div class="system-requirements-header mb-4">
                    <p class="text-sm text-muted">Periksa status dependency dan konfigurasi
                        sistem.</p>
                    <button type="button" id="system-req-refresh"
                        class="sysreq-refresh-btn">
                        <svg class="w-4 h-4" viewBox="0 0 24 24" fill="currentColor">
                            <path
                                d="M12 6V3L8 7l4 4V8c2.76 0 5 2.24 5 5a5 5 0 0 1-5 5 5 5 0 0 1-4.33-2.5h-2.3A7 7 0 0 0 12 20a7 7 0 0 0 7-7c0-3.87-3.13-7-7-7z" />
                        </svg>
                        Refresh Status
                    </button>
                </div>

                <div class="system-req-loading text-center py-8 hidden" id="system-req-loading">
                    <svg class="animate-spin w-8 h-8 mx-auto" viewBox="0 0 24 24" fill="none">
                        <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4">
                        </circle>
                        <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z">
                        </path>
                    </svg>
                    <p class="text-sm text-muted mt-2">Memeriksa sistem...</p>
                </div>

                <div class="system-req-content" id="system-req-content">
                    <div class="d-flex flex-col gap-3">
                        <!-- PHP Version -->
                        <div class="sysreq-item"
                            id="req-php">
                            <div class="sysreq-icon"
                                id="req-php-icon">
                                <svg class="w-4 h-4" viewBox="0 0 24 24" fill="currentColor">
                                    <path
                                        d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm1 17h-2v-2h2v2zm2.07-7.75l-.9.92C13.45 12.9 13 13.5 13 15h-2v-.5c0-1.1.45-2.1 1.17-2.83l1.24-1.26c.37-.36.59-.86.59-1.41 0-1.1-.9-2-2-2s-2 .9-2 2H8c0-2.21 1.79-4 4-4s4 1.79 4 4c0 .88-.36 1.68-.93 2.25z" />
                                </svg>
                            </div>
                            <div class="sysreq-info">
                                <div class="d-flex items-center justify-between gap-2">
                                    <span class="sysreq-name">PHP Version</span>
                                    <span
                                        class="sysreq-badge"
                                        id="req-php-status">Checking...</span>
                                </div>
                                <p class="sysreq-detail"
                                    id="req-php-detail">Minimal PHP 7.4</p>
                            </div>
                        </div>

                        <!-- PHP Extensions -->
                        <div class="sysreq-item"
                            id="req-extensions">
                            <div class="sysreq-icon"
                                id="req-ext-icon">
                                <svg class="w-4 h-4" viewBox="0 0 24 24" fill="currentColor">
                                    <path
                                        d="M20.5 11H19V7c0-1.1-.9-2-2-2h-4V3.5C13 2.12 11.88 1 10.5 1S8 2.12 8 3.5V5H4c-1.1 0-1.99.9-1.99 2v3.8H3.5c1.49 0 2.7 1.21 2.7 2.7s-1.21 2.7-2.7 2.7H2V20c0 1.1.9 2 2 2h3.8v-1.5c0-1.49 1.21-2.7 2.7-2.7s2.7 1.21 2.7 2.7V22H17c1.1 0 2-.9 2-2v-4h1.5c1.38 0 2.5-1.12 2.5-2.5S21.88 11 20.5 11z" />
                                </svg>
                            </div>
                            <div class="sysreq-info">
                                <div class="d-flex items-center justify-between gap-2">
                                    <span class="sysreq-name">PHP Extensions</span>
                                    <span
                                        class="sysreq-badge"
                                        id="req-ext-status">Checking...</span>
                                </div>
                                <p class="sysreq-detail"
                                    id="req-ext-detail">zip, json, fileinfo, mbstring</p>
                            </div>
                        </div>

                        <!-- 7-Zip -->
                        <div class="sysreq-item"
                            id="req-7zip">
                            <div class="sysreq-icon"
                                id="req-7zip-icon">
                                <svg class="w-4 h-4" viewBox="0 0 24 24" fill="currentColor">
                                    <path
                                        d="M20 6h-8l-2-2H4c-1.1 0-1.99.9-1.99 2L2 18c0 1.1.9 2 2 2h16c1.1 0 2-.9 2-2V8c0-1.1-.9-2-2-2zm-2 6h-2v2h2v2h-2v2h-2v-2h2v-2h-2v-2h2v-2h-2v-2h2v2h2v2z" />
                                </svg>
                            </div>
                            <div class="sysreq-info">
                                <div class="d-flex items-center justify-between gap-2">
                                    <span class="sysreq-name">7-Zip / p7zip</span>
                                    <span
                                        class="sysreq-badge"
                                        id="req-7zip-status">Checking...</span>
                                </div>
                                <p class="sysreq-detail"
                                    id="req-7zip-detail">Untuk ekstraksi .7z, .rar, .tar.gz</p>
                            </div>
                        </div>

                        <!-- File Permissions -->
                        <div class="sysreq-item"
                            id="req-perms">
                            <div class="sysreq-icon"
                                id="req-perms-icon">
                                <svg class="w-4 h-4" viewBox="0 0 24 24" fill="currentColor">
                                    <path
                                        d="M19 3H5c-1.11 0-2 .9-2 2v14c0 1.1.89 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zm-2 10h-4v4h-2v-4H7v-2h4V7h2v4h4v2z" />
                                </svg>
                            </div>
                            <div class="sysreq-info">
                                <div class="d-flex items-center justify-between gap-2">
                                    <span class="sysreq-name">Directory
                                        Permissions</span>
                                    <span
                                        class="sysreq-badge"
                                        id="req-perms-status">Checking...</span>
                                </div>
                                <p class="sysreq-detail"
                                    id="req-perms-detail">file/, logs/, .trash/</p>
                            </div>
                        </div>

                        <!-- Server Info -->
                        <div class="sysreq-item"
                            id="req-server">
                            <div class="sysreq-icon"
                                id="req-server-icon">
                                <svg class="w-4 h-4" viewBox="0 0 24 24" fill="currentColor">
                                    <path
                                        d="M20 13H4c-.55 0-1 .45-1 1v6c0 .55.45 1 1 1h16c.55 0 1-.45 1-1v-6c0-.55-.45-1-1-1zM7 19c-1.1 0-2-.9-2-2s.9-2 2-2 2 .9 2 2-.9 2-2 2zM20 3H4c-.55 0-1 .45-1 1v6c0 .55.45 1 1 1h16c.55 0 1-.45 1-1V4c0-.55-.45-1-1-1zM7 9c-1.1 0-2-.9-2-2s.9-2 2-2 2 .9 2 2-.9 2-2 2z" />
                                </svg>
                            </div>
                            <div class="sysreq-info">
                                <div class="d-flex items-center justify-between gap-2">
                                    <span class="sysreq-name">Server
                                        Information</span>
                                    <span
                                        class="sysreq-badge sysreq-badge-info"
                                        id="req-server-status">Info</span>
                                </div>
                                <p class="sysreq-detail"
                                    id="req-server-detail">Loading...</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <footer
            class="settings-footer flex-shrink-0">
            <button type="button" id="settings-save" data-action="settings-save"
                class="settings-button primary">Simpan</button>
            <button type="button" id="settings-cancel" data-action="settings-cancel"
                class="settings-button outline">Tutup</button>
        </footer>
    </div>
</div>